providers:
  file:
    filename: ./dynamic.yml
  consulCatalog:
    exposedByDefault: false
    prefix: traefik
    endpoint:
      address: 127.0.0.1:8500
      datacenter: tutorialinux

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
  traefik:
    address: ":8080"

api:
  dashboard: true
  insecure: true

log:
  level: "DEBUG"

# log:
#   filePath: "/var/log/traefik.log"

# accessLog:
#   filePath: "/var/log/traefik_access.log"
